set schema public;

drop table IF EXISTS RECIPESINGRS;
drop table IF EXISTS RECIPES;


--drop table IF EXISTS INGREDIENTS;

create table RECIPES (
    ID INT PRIMARY KEY AUTO_INCREMENT NOT NULL ,
    TITLE VARCHAR(20) NOT NULL,
    DESCRIPTION VARCHAR(1000)
);

CREATE UNIQUE INDEX IF NOT EXISTS UNIQUE_INDEX ON RECIPES(TITLE);



--create table INGREDIENTS (
--    ID INT PRIMARY KEY  AUTO_INCREMENT NOT NULL,
--    TITLE VARCHAR(20) NOT NULL
--);

--CREATE UNIQUE INDEX IF NOT EXISTS UNIQUE_INDEX ON INGREDIENTS(TITLE);

CREATE TABLE RECIPESINGRS (
    id INT PRIMARY KEY  AUTO_INCREMENT NOT NULL,
    recipeid INT NOT NULL,
--    INGREDIENT_ID INT NOT NULL,
    ingredient VARCHAR(20) NOT NULL,
    amount INT
--FOREIGN KEY (RECIPE_ID)  REFERENCES RECIPES (ID) ON DELETE CASCADE
--    FOREIGN KEY (INGREDIENT_ID)  REFERENCES INGREDIENTS (ID) ON DELETE CASCADE
);
--INSERT INTO INGREDIENTS (title) values('potato');




